version: "3.8"

services:
  odoo:
    image: odoo:18.0
    depends_on:
      - db
    ports:
      - "${ODOO_PORT}:8069"
    volumes:
      - ./addons:/mnt/extra-addons
      - ./etc:/etc/odoo
    environment:
      - HOST=${ODOO_DB_HOST}
      - USER=${ODOO_DB_USER}
      - PASSWORD=${ODOO_DB_PASSWORD}
    command: ["odoo", "-c", "/etc/odoo/odoo.conf"]
    restart: unless-stopped