version: "3.8"

services:
  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
    ports:
      - "5432:5432"
    volumes:
      - odoo18-db-data:/var/lib/postgresql/data
    restart: unless-stopped

  odoo:
    image: odoo:18.0
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - ./addons:/mnt/extra-addons
      - ./etc:/etc/odoo
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo@20092299
    command: ["odoo", "-c", "/etc/odoo/odoo.conf"]
    restart: unless-stopped

volumes:
  odoo18-db-data: